services:
  - type: web
    name: fbclone-backend
    env: python
    buildCommand: pip install -r facebook/requirements.txt
    startCommand: gunicorn facebook.fbdata:app
    envVars:
      - key: DB_NAME
        value: your_db_name
      - key: DB_USER
        value: your_db_user
      - key: DB_PASSWORD
        value: your_db_password
      - key: DB_HOST
        value: your_db_host
      - key: DB_PORT
        value: 5432
